name: Checks

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.2

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.2
          install-only: true
      - name: golangci-lint fmt
        run: golangci-lint fmt
      - name: check fmt
        run: git diff --exit-code

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'

      - name: Test
        working-directory: ./
        run: go test -v ./...